databases:
  - name: e_commerce_v2
    databaseName: e_commerce_v2
    user: e_commerce_v2

services:
  - type: web
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn e_commerce_v2.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: e_commerce_v2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4