# Generated by Django 4.1.6 on 2023-02-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='media/images/avatars/default_avatar.jpeg', upload_to='userprofile'),
        ),
    ]
